# Generated by Django 5.2.7 on 2025-10-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_team"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="team.team",
            ),
        ),
    ]
