# Generated by Django 5.2.7 on 2025-10-28 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_client_team"),
        ("team", "0003_team_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="team.team",
            ),
            preserve_default=False,
        ),
    ]
