# Generated by Django 5.2.7 on 2026-01-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0006_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="lead.lead",
            ),
        ),
    ]
