# Generated by Django 5.2.7 on 2026-01-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_client_team"),
        ("lead", "0007_alter_comment_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="lead.lead",
            ),
        ),
    ]
